// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RootCause.Data.Context;

#nullable disable

namespace RootCause.Data.Migrations
{
    [DbContext(typeof(BugDBContext))]
    partial class BugDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("RootCause.Core.Entities.Bug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Serverity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StackTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeToSolve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bugs");
                });
#pragma warning restore 612, 618
        }
    }
}
